#!/bin/bash
# opkobling (C) 2018 Martin Østergaard
# Released Under MIT license.
# This script is used to fetch end of day stock exchange information.
# Note i fetch from the danish stock exchange, well because i'm danish :)
# You need to change this if you want stock information from somewhere else.
# you can change the date format on the fetched files, i used danish notation.

#https://www.netfonds.no/quotes/exchange.php?exchange=CPH&at_day=25&at_month=6&at_year=2018&format=csv


d=`date "+%d"`;
y=`date "+%Y"`;
m=`date "+%m"`;

http='https://www.netfonds.no/quotes/exchange.php?exchange=CPH';
atday='&at_day=';
atmonth='&at_month=';
atyear='&at_year=';
format='&format=csv';
# construct String

str="$http$atday$d$atmonth$m$atyear$y$format";

echo $str;


wget "$str" --output-document=`date '+%d-%m-%Y'`.csv ; # snyder lidt med den sidste :P

#wget 'https://www.netfonds.no/quotes/exchange.php?exchange=CPH&at_day=`date '+%d'`&at_month=`date '+%m'`&at_year=`date '+%Y'`&format=csv' --output-document=`date '+%d-%m-%Y'`.csv
